=== rdkcentral/BundleGen/bundlegen/schema/appMetadataSchema.json
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "type": {"type": "string"},
        "version": {"type": "string"},
        "description": {"type": "string"},
        "priority": {"type": "string"},
        "graphics": {"type": "boolean"},
        "network": {
            "type": "object",
            "properties": {
                "type": {"type": "string"}
            },
            "required": ["type"]
        },
        "storage": {"type": "object"},
        "resources": {
            "type": "object",
            "properties": {
                "ram": {"type": "string"}
            },
            "required": ["ram"]
        },
        "features": {
            "type": "array",
            "items": {}
        },
        "mounts": {
            "type": "array",
            "items": {}
        },
	"priority": {"type": "string"}
    },
    "required": [
        "id",
        "type",
        "graphics",
        "network",
        "storage",
        "resources"
    ]
}

=== rdkcentral/BundleGen/sample_app_metadata/youi_reference.json
{
    "id": "com.rdk.youi",
    "type": "application/vnd.rdk-app.dac.native",
    "graphics": true,
    "network": {
        "type": "open",
        "dnsmasq": "true"
    },
    "storage": {
        "persistent": [
            {
                "size": "60M",
                "path": "/home/private"
            }
        ],
        "temp": [
            {
                "size": "100M",
                "path": "/home/temp"
            },
            {
                "size": "10M",
                "path": "/var/volatile"
            }
        ]
    },
    "resources": {
        "ram": "256M"
    },
    "features": [],
    "mounts": []
}

=== rdkcentral/BundleGen/sample_app_metadata/flutter.json
{
    "id": "com.rdk.flutter",
    "type": "application/vnd.rdk-app.dac.native",
    "graphics": true,
    "network": {
        "type": "nat",
        "dnsmasq": "true"
    },
    "storage": {
        "persistent": [
            {
                "size": "60M",
                "path": "/home/private"
            }
        ],
        "temp": [
            {
                "size": "100M",
                "path": "/home/temp"
            },
            {
                "size": "10M",
                "path": "/var/volatile"
            }
        ]
    },
    "resources": {
        "ram": "256M"
    },
    "features": [],
    "mounts": []
}

=== rdkcentral/BundleGen/sample_app_metadata/helloworld.json
{
    "id": "com.docker.helloworld",
    "type": "application/vnd.rdk-app.dac.native",
    "graphics": false,
    "network": {
        "type": "open"
    },
    "storage": {
        "persistent": [
            {
                "size": "60M",
                "path": "/home/private"
            }
        ],
        "temp": [
            {
                "size": "100M",
                "path": "/home/temp"
            },
            {
                "size": "10M",
                "path": "/var/volatile"
            }
        ]
    },
    "resources": {
        "ram": "5M"
    },
    "features": [],
    "mounts": []
}
