=== rdkcentral/BundleGen/bundlegen/schema/platformSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "type": "object",
    "properties": {
        "platformName": {"type": "string"},
        "os": {"type": "string"},
        "arch": {"$ref": "#/$defs/arch_type"},
        "rdk": {"$ref": "#/$defs/rdk_type"},
        "hardware": {"$ref": "#/$defs/hardware_type"},
        "storage": {"$ref": "#/$defs/storage_type"},
        "gpu": {"$ref": "#/$defs/gpu_type"},
        "mounts": {"$ref": "#/$defs/mounts_type"},
        "network": {"$ref": "#/$defs/network_type"},
        "envvar": {"$ref": "#/$defs/supportedFeatures_type"},
        "resourceLimits": {"$ref": "#/$defs/resourceLimits_type"},
        "disableUserNamespacing": {"type": "boolean"},
	"root": {"$ref": "#/$defs/root_type"},
	"hostname": {"type": "string"},
	"dobby": {"$ref": "#/$defs/dobby_type"},
	"logging": {"$ref": "#/$defs/logging_type"},
	"tarball": {"$ref": "#/$defs/tarball_type"}
    },
    "required": [
        "platformName",
        "os",
        "arch",
        "rdk",
        "hardware",
        "network"
    ],
    "$defs": {
        "arch_type": {
            "type": "object",
            "properties": {
                "arch": {"type": "string"},
                "variant": {"type": "string"}
            },
            "required": [
                "arch"
            ]
        },
	"usersAndGroups_type": {
            "type": "object",
            "properties": {
                "uid": {"type": "string"},
                "variant": {"type": "string"}
            },
            "required": [
                "arch"
            ]
        },
        "supportedFeatures_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        },
        "rdk_type": {
            "type": "object",
            "properties": {
                "version": {"type": "string"},
                "supportedFeatures": {"$ref": "#/$defs/supportedFeatures_type"}
            },
            "required": [
                "version",
                "supportedFeatures"
            ]
        },
        "hardware_type": {
            "type": "object",
            "properties": {
                "graphics": {"type": "boolean"},
                "maxRam": {"type": "string"}
            },
            "required": [
                "graphics"
            ]
        },
        "persistent_type": {
            "type": "object",
            "properties": {
                "storageDir": {"type": "string"},
                "maxSize": {"type": "string"},
		"minSize": {"type": "string"},
		"fstype": {"type": "string"},
		"maxTotalSize": {"type": "string"}
            },
            "required": [
                "storageDir"
            ]
        },
	"temp_type": {
            "type": "object",
            "properties": {
                "maxSize": {"type": "string"},
		"minSize": {"type": "string"},
		"maxTotalSize": {"type": "string"}
            }
        },
        "storage_type": {
            "type": "object",
            "properties": {
                "persistent": {"$ref": "#/$defs/persistent_type"},
		"temp": {"$ref": "#/$defs/temp_type"}
            }
        },
	"options_type": {
            "type": "array",
            "minItems": 0,
            "items": {"type": "string"}
        },
        "extraMounts_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "source": {"type": "string"},
                    "destination": {"type": "string"},
                    "options": {"$ref": "#/$defs/options_type"}
                },
                "required": [
                    "destination"
                ]
            }
        },
        "devs_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "type": {"type": "string"},
                    "path": {"type": "string"},
                    "major": {"type": "integer"},
                    "minor": {"type": "integer"},
		    "fileMode": {"type": "integer"},
		    "uid": {"type": "integer"},
		    "gid": {"type": "integer"},
                    "access": {"type": "string"}
                },
                "required": [
                    "type",
                    "path",
                    "major",
                    "minor"
                ]
            }
        },
        "gfxLibs_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "src": {"type": "string"},
                    "dst": {"type": "string"}
                },
                "required": [
                    "src",
                    "dst"
                ]
            }
        },
	"westeros_type": {
            "type": "object",
            "properties": {
                "hostSocket": {"type": "string"}
            }
        },
        "gpu_type": {
            "type": "object",
            "properties": {
                "extraMounts": {"$ref": "#/$defs/extraMounts_type"},
                "envvar": {"$ref": "#/$defs/supportedFeatures_type"},
                "devs": {"$ref": "#/$defs/devs_type"},
                "gfxLibs": {"$ref": "#/$defs/gfxLibs_type"},
		"westeros": {"$ref": "#/$defs/westeros_type"},
		"waylandDisplay": {"type": "string"}
            },
            "required": [
                "gfxLibs"
            ]
        },
	"root_type": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
		"readonly": {"type": "boolean"}
            }
        },
        "mounts_type": {
            "type": "array",
            "minItems": 0,
	    "items": {
                "type": "object",
                "properties": {
                    "source": {"type": "string"},
                    "destination": {"type": "string"},
                    "options": {"$ref": "#/$defs/options_type"}
                },
                "required": [
                    "destination"
                ]
            }
        },
        "network_type": {
            "type": "object",
            "properties": {
                "options": {"$ref": "#/$defs/supportedFeatures_type"}
            },
            "required": ["options"]
        },
        "resourceLimits_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "type": {"type": "string"},
                    "hard": {"type": "integer"},
                    "soft": {"type": "integer"}
                },
                "required": [
                    "type",
                    "hard",
                    "soft"
                ]
            }
        },
        "logging_type": {
        	"type": "object",
            	"properties": {
                "mode": {
		    "type": "string",
		    "enum": ["file", "journald", "devnull"]
		},
                "logDir": {"type": "string"}
            	},
	    	"if": {
			"properties": { "mode": {"const": "file"}}
	    	},
	    	"then": {
			"required": [
		    		"mode",
		    		"logDir"
			]
	    	},
	    	"else": {
			"required": [
	   	    		"mode"
			]
		}
        },
	"dobby_type": {
		"type": "object",
		"properties": {
			"pluginDir": {"type": "string"},
			"pluginDependencies": {"$ref": "#/$defs/supportedFeatures_type"},
			"dobbyInitPath": {"type": "string"},
			"generateCompliantConfig": {"type": "boolean"},
			"hookLauncherExecutablePath": {"type": "string"},
			"hookLauncherParametersPath": {"type": "string"}
		}
	},
	"tarball_type": {
		"type": "object",
		"properties": {
			"fileOwnershipSameAsUser": {"type": "boolean"},
			"fileMask":  {"type": "string"}
		}
	}
    }
}

=== rdkcentral/BundleGen/templates/generic/rpi4_64_reference_bb_kirkstone.json
{
    "platformName": "rpi4_64_reference",
    "os": "linux",
    "arch": {
        "arch": "aarch64",
        "variant": "v8"
    },
    "rdk": {
        "version": "2024Q3",
        "supportedFeatures": [
            "DeviceInfo",
            "org.rdk.Network",
            "org.rdk.OCIContainer",
            "org.rdk.Proxies"
        ]
    },
    "hardware": {
            "graphics":false
    },
    "storage": {
        "persistent": {
            "storageDir": "/opt/dac_apps/data/0",
            "maxSize": "100M"
        }
    },
    "gpu": {
        "extraMounts": [
            {
                "source": "/etc/ssl/certs",
                "destination": "/etc/ssl/certs",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/usr/share/ca-certificates",
                "destination": "/usr/share/ca-certificates",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            }
        ],
        "envvar": [
            "XDG_RUNTIME_DIR=/tmp"
        ],
        "devs": [
        ],
        "gfxLibs": [
        ]
    },
    "mounts": [
        {
            "source": "/usr/lib/libstdc++.so.6",
            "destination": "/usr/lib/libstdc++.so.6",
            "options": [
                "rbind",
                "nosuid",
                "nodev",
                "ro"
            ],
            "type": "bind"
        },
        {
            "source": "/lib/libgcc_s.so.1",
            "destination": "/lib/libgcc_s.so.1",
            "options": [
                "rbind",
                "nosuid",
                "nodev",
                "ro"
            ],
            "type": "bind"
        },
       {
            "source": "tmpfs",
            "destination": "/tmp",
            "options": [
                "nosuid",
                "strictatime",
                "mode=755",
                "size=65536k"
            ],
            "type": "tmpfs"
        }
    ],
    "network": {
        "options": [
            "nat",
            "open",
            "private"
        ]
    },
    "envvar": [
    ],
    "resourceLimits": [
        {
            "type": "RLIMIT_NPROC",
            "hard": 300,
            "soft": 300
        },
        {
            "type": "RLIMIT_RTPRIO",
            "hard": 6,
            "soft": 6
        }
    ],
    "disableUserNamespacing": true,
    "logging": {
        "mode": "file",
        "logDir": "/var/log"
    }
}

=== rdkcentral/BundleGen/templates/lgi/brcm972180hbc-refboard-TR0003667.json
{
    "platformName": "brcm972180hbc-refboard-TR0003667",
    "os": "linux",
    "arch": {
        "arch": "arm",
        "variant": "v7"
    },
    "rdk": {
        "version": "2020Q4",
        "supportedFeatures": [
            "Controller",
            "DeviceInfo",
            "Monitor",
            "OCDM",
            "TraceControl",
            "WifiManager",
            "com.comcast.CoPilot",
            "com.comcast.DeviceProvisioning",
            "com.comcast.FrameRate",
            "com.comcast.HdcpProfile",
            "com.comcast.HdmiInput",
            "com.comcast.StateObserver",
            "com.comcast.StorageManager",
            "org.rdk.ActivityMonitor",
            "org.rdk.DeviceDiagnostics",
            "org.rdk.DisplaySettings",
            "org.rdk.FrontPanel",
            "org.rdk.HomeNetworking",
            "org.rdk.LoggingPreferences",
            "org.rdk.Network",
            "org.rdk.OCIContainer",
            "org.rdk.Proxies",
            "org.rdk.SleepTimer",
            "org.rdk.TTSResource",
            "org.rdk.TTSSettings",
            "org.rdk.Timer",
            "org.rdk.UserPreferences",
            "org.rdk.Warehouse"
        ]
    },
    "hardware": {
        "graphics": true
    },
    "storage": {
        "persistent": {
            "storageDir": "/opt/dac_apps/data/0",
            "maxSize": "100M"
        }
    },
    "gpu": {
        "extraMounts": [
            {
                "source": "/usr/share/X11/xkb",
                "destination": "/usr/share/X11/xkb",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/tmp/nxserver_ipc",
                "destination": "/tmp/nxserver_ipc",
                "type": "bind",
                "options": [
                    "bind",
                    "ro"
                ]
            },
            {
                "source": "/etc/ssl/certs",
                "destination": "/etc/ssl/certs",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/usr/share/ca-certificates",
                "destination": "/usr/share/ca-certificates",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/tmp/{id}",
                "destination": "/tmp/rialto-0",
                "type": "bind",
                "options": [
                    "rbind",
                    "rw",
                    "X-dobby.optional"
                ]
            }
        ],
        "args": [
            "/usr/libexec/DobbyInit",
            "/usr/bin/essos-egl"
        ],
        "envvar": [
            "LD_PRELOAD=/usr/lib/libwayland-client.so.0:/usr/lib/libwayland-egl.so.0",
            "XDG_RUNTIME_DIR=/tmp",
            "RIALTO_SOCKET_PATH=/tmp/rialto-0"
        ],
        "devs": [
            {
                "type": "c",
                "path": "/dev/nexus",
                "major": 33,
                "minor": 0,
                "access": "rw"
            },
            {
                 "type": "c",
                 "path": "/dev/dri/card0",
                 "major": 226,
                 "minor": 0,
                 "access": "rw"
            },
            {
                 "type": "c",
                 "path": "/dev/dri/card1",
                 "major": 226,
                 "minor": 1,
                 "access": "rw"
            }
        ],
        "gfxLibs": [
            {
                "src": "/usr/lib/libEGL.so.1",
                "dst": "/usr/lib/libEGL.so"
            },
            {
                "src": "/usr/lib/libEGL.so.1",
                "dst": "/usr/lib/libEGL.so.1"
            },
            {
                "src": "/usr/lib/libGLESv2.so.2",
                "dst": "/usr/lib/libGLESv2.so"
            },
            {
                "src": "/usr/lib/libGLESv2.so.2",
                "dst": "/usr/lib/libGLESv2.so.2"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so.0"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so.1"
            },
            {
                "src": "/usr/lib/libessos.so.0",
                "dst": "/usr/lib/libessos.so.0"
            }
        ]
    },
    "mounts": [],
    "network": {
        "options": [
            "nat",
            "open",
            "private"
        ]
    },
    "envvar": [
    ],
    "resourceLimits": [
        {
            "type": "RLIMIT_NPROC",
            "hard": 300,
            "soft": 300
        },
        {
            "type": "RLIMIT_RTPRIO",
            "hard": 6,
            "soft": 6
        }
    ],
    "disableUserNamespacing": true,
    "logging": {
        "mode": "file",
        "logDir": "/var/log"
    }
}

=== rdkcentral/BundleGen/templates/generic/rpi3_reference_vc4_dunfell.json
{
    "platformName": "rpi3_reference",
    "os": "linux",
    "arch": {
        "arch": "arm",
        "variant": "v7"
    },
    "rdk": {
        "version": "2020Q4",
        "supportedFeatures": [
            "Controller",
            "DeviceInfo",
            "Monitor",
            "OCDM",
            "TraceControl",
            "WifiManager",
            "com.comcast.CoPilot",
            "com.comcast.DeviceProvisioning",
            "com.comcast.FrameRate",
            "com.comcast.HdcpProfile",
            "com.comcast.HdmiInput",
            "com.comcast.StateObserver",
            "com.comcast.StorageManager",
            "org.rdk.ActivityMonitor",
            "org.rdk.DeviceDiagnostics",
            "org.rdk.DisplaySettings",
            "org.rdk.FrontPanel",
            "org.rdk.HomeNetworking",
            "org.rdk.LoggingPreferences",
            "org.rdk.Network",
            "org.rdk.OCIContainer",
            "org.rdk.Proxies",
            "org.rdk.SleepTimer",
            "org.rdk.TTSResource",
            "org.rdk.TTSSettings",
            "org.rdk.Timer",
            "org.rdk.UserPreferences",
            "org.rdk.Warehouse"
        ]
    },
    "hardware": {
        "graphics": true
    },
    "storage": {
        "persistent": {
            "storageDir": "/opt/dac_apps/data/0/dac",
            "maxSize": "100M"
        }
    },
    "gpu": {
        "extraMounts": [
            {
                "source": "/usr/share/X11/xkb",
                "destination": "/usr/share/X11/xkb",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/etc/ssl/certs",
                "destination": "/etc/ssl/certs",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/usr/share/ca-certificates",
                "destination": "/usr/share/ca-certificates",
                "type": "bind",
                "options": [
                    "rbind",
                    "nosuid",
                    "nodev",
                    "ro",
                    "X-mount.mkdir"
                ]
            },
            {
                "source": "/tmp/rialto-0",
                "destination": "/tmp/rialto-0",
                "type": "bind",
                "options": [
                    "rbind",
                    "rw",
                    "X-dobby.optional"
                ]
            }
        ],
        "envvar": [
            "LD_PRELOAD=/usr/lib/libGLESv2.so.2:/usr/lib/libwayland-egl.so.1"
        ],
        "devs": [
            {
                "type": "c",
                "path": "/dev/vchiq",
                "major": 243,
                "minor": 0,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/snd/controlC0",
                "major": 116,
                "minor": 0,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/snd/seq",
                "major": 116,
                "minor": 1,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/snd/pcmC0D0p",
                "major": 116,
                "minor": 16,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/snd/pcmC0D1p",
                "major": 116,
                "minor": 17,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/snd/timer",
                "major": 116,
                "minor": 33,
                "access": "rw"
            },
            {
                "type": "c",
                "path": "/dev/dri/card0",
                "major": 226,
                "minor": 0,
                "access": "rw"
            }
        ],
        "gfxLibs": [
            {
                "src": "/usr/lib/dri/vc4_dri.so",
                "dst": "/usr/lib/dri/vc4_dri.so"
            },
            {
                "src": "/usr/lib/libEGL.so.1",
                "dst": "/usr/lib/libEGL.so"
            },
            {
                "src": "/usr/lib/libEGL.so.1",
                "dst": "/usr/lib/libEGL.so.1"
            },
            {
                "src": "/usr/lib/libGLESv2.so.2",
                "dst": "/usr/lib/libGLESv2.so"
            },
            {
                "src": "/usr/lib/libGLESv2.so.2",
                "dst": "/usr/lib/libGLESv2.so.2"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so.0"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.1",
                "dst": "/usr/lib/libwayland-egl.so.1"
            },
            {
                "src": "/usr/lib/libessos.so.0",
                "dst": "/usr/lib/libessos.so.0"
            }
        ]
    },
    "mounts": [],
    "network": {
        "options": [
            "nat",
            "open",
            "private"
        ]
    },
    "envvar": [
        "XDG_RUNTIME_DIR=/tmp"
    ],
    "resourceLimits": [
        {
            "type": "RLIMIT_NPROC",
            "hard": 300,
            "soft": 300
        },
        {
            "type": "RLIMIT_RTPRIO",
            "hard": 6,
            "soft": 6
        }
    ],
    "disableUserNamespacing": true,
    "logging": {
        "mode": "file",
        "logDir": "/var/log"
    }
}

=== rdkcentral/BundleGen/templates/generic/rpi3.json
{
    "platformName": "rpi3",
    "os": "linux",
    "arch": {
        "arch": "arm",
        "variant": "v7"
    },
    "rdk": {
        "version": "2020Q4",
        "supportedFeatures": [
            "Controller",
            "DeviceInfo",
            "Monitor",
            "OCDM",
            "TraceControl",
            "WifiManager",
            "com.comcast.CoPilot",
            "com.comcast.DeviceProvisioning",
            "com.comcast.FrameRate",
            "com.comcast.HdcpProfile",
            "com.comcast.HdmiInput",
            "com.comcast.StateObserver",
            "com.comcast.StorageManager",
            "org.rdk.ActivityMonitor",
            "org.rdk.DeviceDiagnostics",
            "org.rdk.DisplaySettings",
            "org.rdk.FrontPanel",
            "org.rdk.HomeNetworking",
            "org.rdk.LoggingPreferences",
            "org.rdk.Network",
            "org.rdk.OCIContainer",
            "org.rdk.Proxies",
            "org.rdk.SleepTimer",
            "org.rdk.TTSResource",
            "org.rdk.TTSSettings",
            "org.rdk.Timer",
            "org.rdk.UserPreferences",
            "org.rdk.Warehouse"
        ]
    },
    "hardware": {
        "graphics": true,
        "maxRam": "610M"
    },
    "storage": {
        "persistent": {
            "storageDir": "/tmp/data",
            "maxSize": "100M"
        }
    },
    "gpu": {
        "westeros": {
        },
        "extraMounts": [
        ],
        "envvar": [
            "LD_PRELOAD=/usr/lib/libwayland-client.so.0:/usr/lib/libwayland-egl.so.0"
        ],
        "devs": [
            {
                "type": "c",
                "path": "/dev/vchiq",
                "major": 245,
                "minor": 0,
                "access": "rw"
            }
        ],
        "gfxLibs": [
            {
                "src": "/usr/lib/libEGL.so",
                "dst": "/usr/lib/libEGL.so"
            },
            {
                "src": "/usr/lib/libEGL.so",
                "dst": "/usr/lib/libEGL.so.1"
            },
            {
                "src": "/usr/lib/libGLESv2.so",
                "dst": "/usr/lib/libGLESv2.so"
            },
            {
                "src": "/usr/lib/libGLESv2.so",
                "dst": "/usr/lib/libGLESv2.so.2"
            },
            {
                "src": "/usr/lib/libwayland-egl.so",
                "dst": "/usr/lib/libwayland-egl.so"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.0",
                "dst": "/usr/lib/libwayland-egl.so.0"
            },
            {
                "src": "/usr/lib/libwayland-egl.so.0",
                "dst": "/usr/lib/libwayland-egl.so.1"
            },
            {
                "src": "/usr/lib/libbcm_host.so",
                "dst": "/usr/lib/libbcm_host.so"
            },
            {
                "src": "/usr/lib/libvchostif.so",
                "dst": "/usr/lib/libvchostif.so"
            },
            {
                "src": "/usr/lib/libvcos.so",
                "dst": "/usr/lib/libvcos.so"
            },
            {
                "src": "/usr/lib/libvchiq_arm.so",
                "dst": "/usr/lib/libvchiq_arm.so"
            },
            {
                "src": "/usr/lib/libwesteros_simpleshell_client.so.0",
                "dst": "/usr/lib/libwesteros_simpleshell_client.so.0"
            },
            {
                "src": "/usr/lib/libwayland-server.so.0",
                "dst": "/usr/lib/libwayland-server.so.0"
            }
        ]
    },
    "mounts": [],
    "network": {
        "options": [
            "nat",
            "open",
            "private"
        ]
    },
    "envvar": [
        "XDG_RUNTIME_DIR=/tmp"
    ],
    "resourceLimits": [
        {
            "type": "RLIMIT_NPROC",
            "hard": 300,
            "soft": 300
        },
        {
            "type": "RLIMIT_RTPRIO",
            "hard": 6,
            "soft": 6
        }
    ],
    "disableUserNamespacing": true,
    "logging": {
        "mode": "file",
        "logDir": "/var/log"
    },
    "dobby": {
        "pluginDir": "/usr/lib/plugins/dobby",
        "pluginDependencies": [
            "/lib/libc.so.6",
            "/lib/libdl.so.2",
            "/lib/libcap.so.2",
            "/lib/libgcc_s.so.1",
            "/lib/libm.so.6",
            "/lib/libpthread.so.0",
            "/lib/libresolv.so.2",
            "/lib/librt.so.1",
            "/lib/libsystemd.so.0",
            "/usr/lib/liblzma.so.5",
            "/usr/lib/libnl-3.so.200",
            "/usr/lib/libnl-route-3.so.200",
            "/usr/lib/libstdc++.so.6",
            "/usr/lib/libyajl.so.2",
            "/lib/ld-linux-armhf.so.3"
        ]
    }
}
